# Generated by Django 4.1.3 on 2022-11-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='back_text',
            new_name='definition',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='front_text',
            new_name='word',
        ),
    ]
